FROM node:22-alpine

WORKDIR /app
RUN npm install -g pnpm
RUN npm install -g typescript

COPY ./package.json ./package.json

RUN pnpm install

COPY . .

RUN pnpm build

EXPOSE 3000
CMD ["pnpm", "start"]