name: Backned-Deployment

on:
  push: 
    branches: 
      - prod
    paths: 
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'
jobs: 
  deploy:
    runs-on: ubuntu-latest
    environment: backend-deployment

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./docker/Dockerfile.backend
          push: true
          tags: ikrambagban/proxlay-backend:${{ github.sha }}
      
      - name: Clone staging-ops repo, update, and push
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git clone  https://github.com/IkramBagban/gitops.git
          cd gitops
          sed -i 's|image: ikrambagban/proxlay-backend:.*|image: ikrambagban/proxlay-backend:${{ github.sha }}|' proxlay/deployment.yml
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add proxlay/deployment.yml
          git commit -m "Update backend image to ${{ github.sha }}"
          git push https://${PAT}@github.com/IkramBagban/gitops.git main